<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_picture</name>
   <tag></tag>
   <elementGuidId>35c001ce-3663-4685-afb9-7d189f425df2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input [contains(@id, 'product_images')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.bi.bi-plus.display-6</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'bi bi-plus display-6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0fb0d344-dcec-47ad-ab05-7064e57f686e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-plus display-6</value>
      <webElementGuid>0d1cafd8-992d-425b-a01d-4573e56be7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-images&quot;)/div[@class=&quot;form-image rounded-4 img-preview&quot;]/i[@class=&quot;bi bi-plus display-6&quot;]</value>
      <webElementGuid>d45a3960-b151-467c-a028-68d25946aa37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='input-images']/div[2]/i</value>
      <webElementGuid>56205daa-fcfe-45a7-b0d4-797250969a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/i</value>
      <webElementGuid>2965d8b6-b636-47a0-8382-bb0c0e2b8b17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
