<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_kota</name>
   <tag></tag>
   <elementGuidId>757baaef-2654-4480-8a01-d9b77a1b1472</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_city_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='user_city_id']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'user_city_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>78a36236-a3ff-4818-b998-1b98adb987d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select rounded-4 p-3</value>
      <webElementGuid>5a083868-9dec-41c0-a2e8-210a755aef4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>b30ac866-65b7-4664-9d34-50cac936d277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user[city_id]</value>
      <webElementGuid>06c14273-9915-4b5a-80dd-86e21bcbe2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_city_id</value>
      <webElementGuid>6abb4e41-6b62-4bdc-8acb-0c0467be94f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Kota
Solo
Jogja
Jakarta
Bandung
Semarang</value>
      <webElementGuid>b29bff58-30fe-4641-826d-45e5ba7ba49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_city_id&quot;)</value>
      <webElementGuid>4223f41f-25de-45ae-ba7a-71851dc0bfc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='user_city_id']</value>
      <webElementGuid>1250f98d-123d-499c-bd4c-4a22752c68b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota'])[1]/following::select[1]</value>
      <webElementGuid>c73cc664-f491-4af2-bd2a-5655cbab8fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[1]/following::select[1]</value>
      <webElementGuid>d1253677-72ef-4bc6-a05a-9037c05885ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[1]/preceding::select[1]</value>
      <webElementGuid>727e3a2c-4d27-4812-9379-0dc1ae89c8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jalan abc 123'])[1]/preceding::select[1]</value>
      <webElementGuid>502262be-d014-4aa3-b7b2-9083ca0e7950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>dbc4804f-b228-4f80-ac29-ec0347b1870e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'user[city_id]' and @id = 'user_city_id' and (text() = 'Pilih Kota
Solo
Jogja
Jakarta
Bandung
Semarang' or . = 'Pilih Kota
Solo
Jogja
Jakarta
Bandung
Semarang')]</value>
      <webElementGuid>7bc719e0-4a36-4566-ad17-894d0da791a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
